# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Joe Knows' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Joe Knows

	source 'https://github.com/CocoaPods/Specs.git'
	target 'Joe KnowsFrameworks' do
	  pod 'GoogleMaps'
	  pod 'GooglePlaces'
	end


  target 'Joe KnowsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Joe KnowsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
